name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up D compiler
        uses: dlang-community/setup-dlang@v1
      - name: Install Pandoc
        run: choco install pandoc
      - name: Check Pandoc version
        run: pandoc --version
      - name: Compile Readme (German) to HTML
        run: pandoc README.md -f markdown -t html -s --metadata pagetitle="ReNeo README" --css docs/gh-pandoc.css -o README.html
      - name: Compile Readme (English) to HTML
        run: pandoc README_EN.md -f markdown -t html -s --metadata pagetitle="ReNeo README" --css docs/gh-pandoc.css -o README_EN.html
      - name: Replace version string in source code
        run: ((Get-Content -path source\app.d -Raw ) -replace '%VERSION%',$Env:GITHUB_REF.Substring(10)) | Set-Content -path source\app.d
      - name: Compile debug version with Dub
        run: dub build --build=debug-log
      - name: Rename debug version
        run: ren reneo.exe reneo_debug.exe
      - name: Compile release version with Dub
        run: dub build --build=release
      - name: Create directory for ZIP file
        run: mkdir ReNeo
      - name: Move release files into directory (except default config)
        run: Move-Item -Path compose,cairo.dll,COPYING,keysymdef.h,layouts.json,README.md,README.html,README_EN.md,README_EN.html,docs,reneo.exe,reneo_debug.exe -Destination ReNeo
      - name: Replace config.default.json with Neo config
        run: mv -Force config.neo.json ReNeo\config.default.json
      - name: Create Neo ZIP file
        run: 7z a -tzip ReNeo_Neo.zip ReNeo\
      - name: Replace config.default.json with NeoQwertz config
        run: mv -Force config.neoqwertz.json ReNeo\config.default.json
      - name: Create NeoQwertz ZIP file
        run: 7z a -tzip ReNeo_NeoQwertz.zip ReNeo\
      - name: Replace config.default.json with Bone config
        run: mv -Force config.bone.json ReNeo\config.default.json
      - name: Create Bone ZIP file
        run: 7z a -tzip ReNeo_Bone.zip ReNeo\
      - name: Replace config.default.json with 3l config
        run: mv -Force config.3l.json ReNeo\config.default.json
      - name: Create 3l ZIP file
        run: 7z a -tzip ReNeo_3l.zip ReNeo\
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          files: |
            ReNeo_Neo.zip
            ReNeo_NeoQwertz.zip
            ReNeo_Bone.zip
            ReNeo_3l.zip
      